### ISSUE TITLE
Inherited Controls have an error for no implementation statement

### ISSUE THREAD

**Issue by TelosPO** [GSA/fedramp-automation#369] opened 2022-12-02 18:04 UTC
* **This is a request**
  - [ ] **concern** - I think something needs to be different.
  - [ ] **question** - I didn't understand something.
  - [ ] **kudos** - I found something helpful and want to encourage it in future FedRAMP publications.
  - [X] **request** - I would like to see something additional provided.

* **This relates to ...**
  - [ ] the **FedRAMP OSCAL Registry** (Excel File)
  - [ ] the **Guide to OSCAL-based FedRAMP Content** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Reports (SAR)** (PDF)
  - [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)** (PDF)
  - [ ] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
  - [ ] **General/Overall**
  - [ X] **Other**

NOTE: For feedback related to the OSCAL syntax itself, please create or add to an [issue in the NIST OSCAL Repository](https://github.com/usnistgov/OSCAL/issues).

* **Where, exactly?**
  - For the registry, please indicate the tab and cell, or other clear identifier
  - For the guide, please indicate the section number and printed page number (lower right corner)
  - For the OSCAL XML or JSON files, please indicate XML or JSON; and indicate the line number, field id, or other clear location identifier

* **What is your feedback?**
The schematron throws an error when a control implementation statement is blank. However when inheriting a control the fully inherited component doesn't have a unique statement (description).

* **What action would you like to see from the FedRAMP PMO?**

Can there be a change to the schematron to for the field to be Informational as opposed to throwing an error when there is not statement?

* **Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, eg. slack, gitter, etc)

**Comment by dimitri-zhurkin-vitg** [comment] 2023-10-17 15:42
Could you please provide the error message?

Without the message, troubleshooting the issue is somewhat cumbersome.

**Comment by aj-stein-gsa** [comment] 2024-10-25 04:22
Re [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md), we will not use the previous constraint architecture as-is and the relevant code will soon be removed. I am closing this issue as not planned.

**Closed by aj-stein-gsa** 2024-10-25 04:22 UTC
Labels: schematron code, Scope: Validation
