### ISSUE TITLE
Errata in SSP Guide

### ISSUE THREAD

**Issue by wendellpiez** [GSA/fedramp-automation#49] opened 2020-08-10 20:27 UTC
Tracking ticket for FedRAMP SSP Guide, Version 2 of August 1, 2020.

**Comment by wendellpiez** [comment] 2020-08-10 20:30
- p 11, Table 202 mapping - where it indicates path `//system-characteristics/system-information/information-type[1]/@name`
  - this should be `//system-characteristics/system-information/information-type[1]/@name`
  - also the OSCAL example (fig 4.3 Information Types) to be updated accordingly

**Comment by ohsh6o** [comment] 2021-05-04 02:19
@wendellpiez , sorry for the delayed response. I will take a look at this in the guidebooks and follow up with you accordingly by later this week.

**Comment by ohsh6o** [comment] 2021-06-01 01:12
This report seems to be a dupe of #39, and those documentation changes have been fixed in the draft revisions. Will close this issue in favor of tracking it with #39, and that will close with official publication of draft releases.

**Closed by ohsh6o** 2021-06-01 01:12 UTC
Labels: bug
